POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{"name":"user","password":"quarkus"}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{"name":"admin","password":"quarkus"}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{"name":"user","password":"invalid"}

###
PUT http://localhost:8080/api/v1/users/self/password
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6InVzZXIiLCJncm91cHMiOlsidXNlciJdLCJpYXQiOjE3NDEwMjk0NzgsImV4cCI6MTc0MTAzMzA3OCwianRpIjoiZTliMDljM2QtMDkxNy00OWEwLWJhNTMtNTM2M2FjODY2MjE0In0.UcRKvSGEkgsMlVeApchmjlPmmpHeMFrhdNr50W4lIHXEmhOd2827sbzvHCWmSrUVbTBfHzOAWmvqOnsvr6o-377Apxb8k8-bMU2rX844AKVW09LIxddx8FmTImsC1VTXCDExH6u5qsBilfU1moz_oh2k7X5zBmtKk0a_EvfJq766qEu8kNbZ3OLV0iNILb8tDRyA3WGsrj_r5bG0iUJFplMKTwcuix_uEPpuYfFawg4YlNuGT4KmGLa3r6RcKqqvk2pI4aLsp2SffyxDY_SJPV7YHBVdMo7MQ2Wv6nKyS9XGKXFmxiOGjsHs0_spcbW-30yUJy-C88tf5bUhTDYELg

{"currentPassword":"quarkus","newPassword":"changed"}

###
GET localhost:8080//api/v1/projects
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6InVzZXIiLCJncm91cHMiOlsidXNlciJdLCJpYXQiOjE3NDEwMjk0NzgsImV4cCI6MTc0MTAzMzA3OCwianRpIjoiZTliMDljM2QtMDkxNy00OWEwLWJhNTMtNTM2M2FjODY2MjE0In0.UcRKvSGEkgsMlVeApchmjlPmmpHeMFrhdNr50W4lIHXEmhOd2827sbzvHCWmSrUVbTBfHzOAWmvqOnsvr6o-377Apxb8k8-bMU2rX844AKVW09LIxddx8FmTImsC1VTXCDExH6u5qsBilfU1moz_oh2k7X5zBmtKk0a_EvfJq766qEu8kNbZ3OLV0iNILb8tDRyA3WGsrj_r5bG0iUJFplMKTwcuix_uEPpuYfFawg4YlNuGT4KmGLa3r6RcKqqvk2pI4aLsp2SffyxDY_SJPV7YHBVdMo7MQ2Wv6nKyS9XGKXFmxiOGjsHs0_spcbW-30yUJy-C88tf5bUhTDYELg

###
GET localhost:8080//api/v1/users
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6ImFkbWluIiwiZ3JvdXBzIjpbImFkbWluIiwidXNlciJdLCJpYXQiOjE3NDExNjEwNjYsImV4cCI6MTc0MTE2NDY2NiwianRpIjoiZjcyZTAzOTMtNjcwYi00NTQ3LThjYTQtOGNlNGQ4ZGUyOGU4In0.gDfD8XIbTzf98CCSbzwHxb5RzULnTal_JIinWxWOvtelVi3cVkF9biA6lbfRXsBjPK_aAOCmPLLtp4mCQ7rzt-DFc1bJF-sOssIh7W3dbntxS3DEEa_tOkT_6CWaZSxo9iapKaFon6Sq8my5J7RPk0fGmaNzwoDYMh-YhDzZBPAIfBPN2LOM9HZyrND23iDgh3spP3oGRGB2gurKRIhzrEcV5Su8JVQ_6SDSYu_DFhvbGyi6b-BFtjYjPEqorGh-moaditvkoAo6CdHnNHw5oKFFNbROTFhvLux_u99mnP2HlJ0Hvy7c_I_ducd5kzWEqu5_hRikzZgSRKxQt1p9sA

###
PUT localhost:8080/api/v1/users/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6ImFkbWluIiwiZ3JvdXBzIjpbImFkbWluIiwidXNlciJdLCJpYXQiOjE3NDEwOTE3OTQsImV4cCI6MTc0MTA5NTM5NCwianRpIjoiOGNiNDAxMWEtMWRmNC00NjU5LTg5NjEtNjhjMzE5OTZjMWU1In0.YxlxApKqhJBcvpBMMHfNJt60f-pysFdBy0f6dkQKuFprIkBy8AETqJ7H-ovymEhazPlLahYsqdcQy_qFHxT_FQ9pRl9e7JhgcYhrDJMh0SygtcMFNB45PhB4EZxz29oOp56TgQA20z1Hc-j2w4Mu0qPsmF90m_kDz9tcWuXEHqo6OYz-MjoWWzlGJC7_iORah96puvdIizDo0-dGCjhBjpnlVUUL-5TPNi0rkTgFJaMjJdcjy96lA7c7CyDqDouJU0wGEVyHpt-uPUtnVedEvUSjkPCjZbkeqaGj5HWJ8Ri_VYNPqUD31GooHzD8uaGgChmCoo7oUiSpJxjD6rCt7g

{
    "name": "packtas",
    "password": "passwordas"
}
###
PUT localhost:8080/api/v1/users/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6ImFkbWluIiwiZ3JvdXBzIjpbImFkbWluIiwidXNlciJdLCJpYXQiOjE3NDEwOTE3OTQsImV4cCI6MTc0MTA5NTM5NCwianRpIjoiOGNiNDAxMWEtMWRmNC00NjU5LTg5NjEtNjhjMzE5OTZjMWU1In0.YxlxApKqhJBcvpBMMHfNJt60f-pysFdBy0f6dkQKuFprIkBy8AETqJ7H-ovymEhazPlLahYsqdcQy_qFHxT_FQ9pRl9e7JhgcYhrDJMh0SygtcMFNB45PhB4EZxz29oOp56TgQA20z1Hc-j2w4Mu0qPsmF90m_kDz9tcWuXEHqo6OYz-MjoWWzlGJC7_iORah96puvdIizDo0-dGCjhBjpnlVUUL-5TPNi0rkTgFJaMjJdcjy96lA7c7CyDqDouJU0wGEVyHpt-uPUtnVedEvUSjkPCjZbkeqaGj5HWJ8Ri_VYNPqUD31GooHzD8uaGgChmCoo7oUiSpJxjD6rCt7g

{
    "name": "packtas"
}
###
GET localhost:8080//api/v1/projects
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6ImFkbWluIiwiZ3JvdXBzIjpbImFkbWluIiwidXNlciJdLCJpYXQiOjE3NDEyNjQ4NjIsImV4cCI6MTc0MTI2ODQ2MiwianRpIjoiOTY4MDBmZjMtNzU0NS00ZjVhLWFkODgtODg5M2FiYTBiODc3In0.K9ar0piEcSdm3EjcHU7Np6TX5mAJ0vAeBvjfdBGDQC51QAnIzeibNmixtWQf1wU85Sgdb0LZdIKrmx6PweeLtDn9Ghv_Yz-IwtUWbetufXpER1TI0rZpo6ZsIVj-FTJRrFSWSTWke5fGkXDuCCx_NbHPIlHyOstSpjnKRLKBVbBqNK9o3MK0LCkDctY4m1zoIqsW-ZGdyELbeE4A36K2czfPFqvi8tK1pUL7uG8XRgtMFCLSJep6E551bST0l8cHabFGlxnLIXhs7S6TCrN-1Yh2m5I-93ft7glNUo0POBtzTTjYR4etX0EpM049UzjGkA0EYqOiwnWCyzyGlayxxw

###
GET localhost:8080//api/v1/tasks
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6ImFkbWluIiwiZ3JvdXBzIjpbImFkbWluIiwidXNlciJdLCJpYXQiOjE3NDEyNjQ4NjIsImV4cCI6MTc0MTI2ODQ2MiwianRpIjoiOTY4MDBmZjMtNzU0NS00ZjVhLWFkODgtODg5M2FiYTBiODc3In0.K9ar0piEcSdm3EjcHU7Np6TX5mAJ0vAeBvjfdBGDQC51QAnIzeibNmixtWQf1wU85Sgdb0LZdIKrmx6PweeLtDn9Ghv_Yz-IwtUWbetufXpER1TI0rZpo6ZsIVj-FTJRrFSWSTWke5fGkXDuCCx_NbHPIlHyOstSpjnKRLKBVbBqNK9o3MK0LCkDctY4m1zoIqsW-ZGdyELbeE4A36K2czfPFqvi8tK1pUL7uG8XRgtMFCLSJep6E551bST0l8cHabFGlxnLIXhs7S6TCrN-1Yh2m5I-93ft7glNUo0POBtzTTjYR4etX0EpM049UzjGkA0EYqOiwnWCyzyGlayxxw

###
