DELETE localhost:8080//api/v1/projects/1
Accept: application/json

###
PUT localhost:8080//api/v1/projects/1
Content-Type: application/json

{
    "name": "new-name",
    "version": 0,
    "user": {
        "id": 0
    }
}

###
POST localhost:8080//api/v1/projects
Content-Type: application/json

{
    "name": "project"
}

###
GET localhost:8080//api/v1/projects
Accept: application/json

###
